using Revise
using Todjl

t0=Turbine("hp_throttle")
t1=Turbine("hp1")
t2=Turbine("hp2")
t3=Turbine("ip1")
t4=Turbine("ip2")
t5=Turbine("lp1")
t6=Turbine("lp2")
t7=Turbine("lp3")
t8=Turbine("lp4")
te=Turbine("exhaust")

sp1=Split("hp1after")
sp2=Split("hp2after")
sp3=Split("ip1after")
sp4=Split("ip2after")
sp5=Split("lp1after")
sp6=Split("lp2after")
sp7=Split("lp3after")
sp8=Split("lp4after")

extpipe1=Pipe("extpipe1")
extpipe2=Pipe("extpipe2")
extpipe3=Pipe("extpipe3")
extpipe4=Pipe("extpipe4")
extpipe5=Pipe("extpipe5")
extpipe6=Pipe("extpipe6")
extpipe7=Pipe("extpipe7")
extpipe8=Pipe("extpipe8")


fwh1=FeedwaterHeater("hp1heater")
fwh2=FeedwaterHeater("hp2heater")
fwh3=FeedwaterHeater("hp3heater")
dae=Dearator("dearator")
fwh5=FeedwaterHeater("lp5hater")
fwh6=FeedwaterHeater("lp6heater")
fwh7=FeedwaterHeater("lp7heater")
fwh8=FeedwaterHeater("lp8heater")
cnd=Condensor("cond")

cwp=Pump("cwp")
fwp=Pump("fwp")

sh=GeneralHeater("super heater")
rh=GeneralHeater("reheater")

c_mainsteam=Connection(sh,:out,t0,:in)
c_t0_t1=Connection(t0,:out,t1,:in)
c_t1_sp1=Connection(t1,:out,sp1,:in)
c_sp1_t2=Connection(sp1,:out1,t2,:in)
c_t2_sp2=Connection(t2,:out1,sp2,:in)
c_sp2_rh=Connection(sp2,out1,rh,:in)
c_rh_t3=Connection(rh,:out,t3,:in)
c_t3_sp3=Connection(t3,:out,sp3,:in)
c_sp3_t4=Connection(sp3,out1,t4,:in)
c_t4_sp4=Connection(t4,:out,sp4,:in)
c_sp4_t5=Connection(sp4,:out1,t5,:in)
c_t5_sp5=Connection(t5,:out,sp5,:in)
c_sp5_t6=Connection(sp5,:out1,t6,:in)
c_t6_sp6=Connection(t6,:out1,sp6,:in)
c_sp6_t7=Connection(sp6,:out,t7,:in)
c_t7_sp7=Connection(t7,:out,sp7,:in)
c_sp7_t8=Connection(sp7,:out1,t8,:in)
c_t8_sp8=Connection(t8,:out,sp8,:in)
c_sp8_te=Connection(sp8,:out,te,:in)
c_te_cnd=Connection(te,:out,cnd,:steam)


c_sp1_p1=Connection(sp1,:out2,extpipe1,:in)
c_sp2_p2=Connection(sp2,:out2,extpipe2,:in)
c_sp3_p3=Connection(sp3,:out2,extpipe3,:in)
c_sp4_p4=Connection(sp4,:out2,extpipe4,:in)
c_sp5_p5=Connection(sp5,:out2,extpipe5,:in)
c_sp6_p6=Connection(sp6,:out2,extpipe6,:in)
c_sp7_p7=Connection(sp7,:out2,extpipe7,:in)
c_sp8_p8=Connection(sp8,:out2,extpipe8,:in)

c_p1_fwh1=Connection(extpipe1,:out,fwh1,:steam)
c_p2_fwh2=Connection(extpipe2,:out,fwh2,:steam)
c_p3_fwh3=Connection(extpipe3,:out,fwh3,:steam)
c_p4_dea=Connection(extpipe4,:out,dea,:steam)
c_p5_fwh5=Connection(extpipe5,:out,fwh5,:steam)
c_p6_fwh6=Connection(extpipe6,:out,fwh6,:steam)
c_p7_fwh7=Connection(extpipe7,:out,fwh7,:steam)
c_p8_fwh8=Connection(extpipe8,:out,fwh8,:steam)

cw_fwh1_sh=Conection(fwh1,:waterout,sh,:in)
cw_fwh2_fwh2=Connection(fwh2,:waterout,fwh2,:waterin)
cw_fwh3_fwh2=Connection(fwh3,:waterout,fwh2,:waterin)
cw_fwp_fwh3=Connection(fwp,:out,fwh3,:in)
cw_dea_fwp=Connection(dea,:waterout,fwp,:waterin)
cw_fwh5_dea=Connection(fwh5,:waterout,dea,:waterin)
cw_fwh6_fwh5=Connection(fwh6,:waterout,fwh5,:waterin)
cw_fwh7_fwh6=Connection(fwh7,:waterout,fwh6,:waterin)
cw_fwh8_fwh7=Connection(fwh8,:waterout,fwh7,:waterin)
cw_cwp_fwh8=Connection(cwp,:out,fwh8,:in)
cw_cnd_cwp=Connection(cnd,:waterout,cwp,:in)

cd_fwh1_fwh2=Connection(fwh1,:drain,fwh2,:prevdrain)
cd_fwh2_fwh3=Connection(fwh2,:drain,fwh3,:prevdrain)
cd_fwh3_dea=Connection(fwh3,:drain,dea,:drain)
cd_fwh5_fwh6=Connection(fwh5,:drain,fwh6,:prevdrain)
cd_fwh6_fwh7=Connection(fwh6,:drain,fwh7,:prevdrain)
cd_fwh7_fwh8=Connection(fwh7,:drain,fwh8,:prevdrain)
cd_fwh8_cnd=Connection(fwh8,:drain,cnd,:drain)

